services:
  - type: web
    name: Interview
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Interview:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.2